### ISSUE TITLE
Two mass edits after each other where the first removes all flags leaves a bugged interface

### ISSUE THREAD

**Issue by chvp** [accentor/web#507]
**Describe the bug**

If you do two mass edits after one another where the first removes all flags, the labels for the different sections don't match the actual functionality. Toggling one of the sections restores the right information.

**To reproduce**

1. Go to an album with flags.
2. Mass edit to remove all flags
3. Mass edit again
4. See that the labels are wrong

**Expected behavior**

The labels should be right.

**Screenshots**

![screenshot_2021-06-12-102622](https://user-images.githubusercontent.com/42220376/121770263-aa5a1600-cb68-11eb-97a5-8c9f8527084c.png)

**Desktop:**

- OS: Linux (NixOS)
- Browser: Firefox
- Version: 89

**Comment by robbevp** [comment]
Have notices this as well. Probably something that can be fixed by adding a unique `key` to each section.On 12 Jun 2021 10:28, Charlotte Van Petegem ***@***.***> wrote:
Describe the bug
If you do two mass edits after one another where the first removes all flags, the labels for the different sections don't match the actual functionality. Toggling one of the sections restores the right information.
To reproduce
Go to an album with flags.Mass edit to remove all flagsMass edit againSee that the labels are wrong
Expected behavior
The labels should be right.
Screenshots

Desktop:
OS: Linux (NixOS)Browser: FirefoxVersion: 89
